spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist_db?currentSchema=tasklist
    username: postgres
    password: repa123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql

security:
  jwt:
    secret: YXNkYXNkU0FEc2FkamRmZ3Nsa0pBRExLSkFTRGxuZmdua05TQUpETmpxd2Vqd2VvcXdqcXdsa2pkTEtTQVNEYVNEamRuc2Rn
    access: 3600000
    refresh: 2592000000

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml