spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist_db?currentSchema=tasklist
    username: postgres
    password: repa123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true
    default-schema: tasklist

security:
  jwt:
    secret: YXNkYXNkU0FEc2FkamRmZ3Nsa0pBRExLSkFTRGxuZmdua05TQUpETmpxd2Vqd2VvcXdqcXdsa2pkTEtTQVNEYVNEamRuc2Rn
    access: 3600000
    refresh: 2592000000

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

springdoc:
  override-with-generic-response: false